-- Mise à jour de la table colors
-- À exécuter dans phpMyAdmin

INSERT INTO colors (code, name_fr, name_en) VALUES
('w', 'blanc', 'white'),
('n', 'noir', 'black'),
('n01', 'noir van', 'black van'),
('n02', 'noir arlequin', 'black arlequin'),
('n03', 'noir bicolore', 'black bicolor'),
('n09', 'noir et blanc', 'black with white'),
('n11', 'noir shaded', 'black shaded'),
('n12', 'noir chinchilla', 'black chinchilla'),
('n21', 'noir tigré', 'black tabby'),
('n22', 'noir tigré classique', 'black classic tabby'),
('n23', 'noir tigré mackerel', 'black mackerel tabby'),
('n24', 'noir tigré spotted', 'black spotted tabby'),
('n25', 'noir tigré ticked', 'black ticked tabby'),
('a', 'gris', 'blue'),
('a01', 'gris van', 'blue van'),
('a02', 'gris arlequin', 'blue arlequin'),
('a03', 'gris bicolore', 'blue bicolor'),
('a09', 'gris et blanc', 'blue with white'),
('a11', 'gris shaded', 'blue shaded'),
('a12', 'gris chinchilla', 'blue chinchilla'),
('a21', 'gris tigré', 'blue tabby'),
('a22', 'gris tigré classique', 'blue classic tabby'),
('a23', 'gris tigré mackerel', 'blue mackerel tabby'),
('a24', 'gris tigré spotted', 'blue spotted tabby'),
('a25', 'gris tigré ticked', 'blue ticked tabby'),
('d', 'roux', 'red'),
('d01', 'roux van', 'red van'),
('d02', 'roux arlequin', 'red arlequin'),
('d03', 'roux bicolore', 'red bicolor'),
('d09', 'roux et blanc', 'red with white'),
('d11', 'roux shaded', 'red shaded'),
('d12', 'roux chinchilla', 'red chinchilla'),
('d21', 'roux tigré', 'red tabby'),
('d22', 'roux tigré classique', 'red classic tabby'),
('d23', 'roux tigré mackerel', 'red mackerel tabby'),
('d24', 'roux tigré spotted', 'red spotted tabby'),
('d25', 'roux tigré ticked', 'red ticked tabby'),
('e', 'crème', 'cream'),
('e01', 'crème van', 'cream van'),
('e02', 'crème arlequin', 'cream arlequin'),
('e03', 'crème bicolore', 'cream bicolor'),
('e09', 'crème et blanc', 'cream with white'),
('e11', 'crème shaded', 'cream shaded'),
('e12', 'crème chinchilla', 'cream chinchilla'),
('e21', 'crème tigré', 'cream tabby'),
('e22', 'crème tigré classique', 'cream classic tabby'),
('e23', 'crème tigré mackerel', 'cream mackerel tabby'),
('e24', 'crème tigré spotted', 'cream spotted tabby'),
('e25', 'crème tigré ticked', 'cream ticked tabby'),
('f', 'noir tortie', 'black tortie'),
('f01', 'noir tortie van', 'black tortie van'),
('f02', 'noir tortie arlequin', 'black tortie arlequin'),
('f03', 'noir tortie bicolore', 'black tortie bicolor'),
('f09', 'noir tortie et blanc', 'black tortie with white'),
('f11', 'noir tortie shaded', 'black tortie shaded'),
('f12', 'noir tortie chinchilla', 'black tortie chinchilla'),
('f21', 'noir torbie tigré', 'black torbie'),
('f22', 'noir torbie classique', 'black classic torbie'),
('f23', 'noir torbie mackerel', 'black mackerel torbie'),
('f24', 'noir torbie spotted', 'black spotted torbie'),
('f25', 'noir torbie ticked', 'black ticked torbie'),
('g', 'gris tortie', 'blue tortie'),
('g01', 'gris tortie van', 'blue tortie van'),
('g02', 'gris tortie arlequin', 'blue tortie arlequin'),
('g03', 'gris tortie bicolore', 'blue tortie bicolor'),
('g09', 'gris tortie et blanc', 'blue tortie with white'),
('g11', 'gris tortie shaded', 'blue tortie shaded'),
('g12', 'gris tortie chinchilla', 'blue tortie chinchilla'),
('g21', 'gris tortie tigré', 'blue torbie'),
('g22', 'gris torbie classique', 'blue classic torbie'),
('g23', 'gris torbie mackerel', 'blue mackerel torbie'),
('g24', 'gris torbie spotted', 'blue spotted torbie'),
('g25', 'gris torbie ticked', 'blue ticked torbie')
ON DUPLICATE KEY UPDATE
    name_fr = VALUES(name_fr),
    name_en = VALUES(name_en);
